global:
  resolve_timeout: 5m

route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: 'primary-alerts'

  routes:
    # Safeguarding alerts — notify immediately
    - matchers:
        - severity="critical"
        - team="safeguarding"
      group_wait: 0s
      receiver: 'primary-alerts'

    - matchers:
        - severity="critical"
      receiver: 'primary-alerts'

    - matchers:
        - severity="warning"
      receiver: 'primary-alerts'

receivers:
  - name: 'primary-alerts'
    webhook_configs:
      - url: 'http://webhook-logger:8080/'
        send_resolved: true
    discord_configs:
      - webhook_url: 'https://discord.com/api/webhooks/1512576953113378828/R05PLkf5mNO6tjx2VqY3L_tUVNGkghCXKxAQgVDSGyjgpyfVV3-GnVnEWLSVHXsioSM4'
        send_resolved: true

inhibit_rules:
  - source_matchers: ['severity="critical"']
    target_matchers: ['severity="warning"']
    equal: ['alertname', 'job']
